apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  # namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    # Paste the contents of your existing alertmanager.yaml here
    # ...