apiVersion: v1
kind: Service
metadata:
  name: patient-management-service
  labels:
    app: patient-management
spec:
  type: NodePort
  selector:
    app: patient-management
  ports:
  - name: backend
    port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  - name: frontend
    port: 8000
    targetPort: 8000
    nodePort: 30001
    protocol: TCP
  sessionAffinity: ClientIP